# Generated by Django 5.0.4 on 2024-05-17 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_attendance_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstaff',
            old_name='feebback_reply',
            new_name='feeback_reply',
        ),
        migrations.RenameField(
            model_name='feedbackstudent',
            old_name='feebback_reply',
            new_name='feedback_reply',
        ),
    ]
