# Generated by Django 5.0.4 on 2024-05-17 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_rename_feebback_reply_feedbackstaff_feeback_reply_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackstaff',
            old_name='feeback_reply',
            new_name='feedback_reply',
        ),
    ]
